// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class K2_Billing_AppointmentContext : DbContext
    {
        public K2_Billing_AppointmentContext()
        {
        }

        public K2_Billing_AppointmentContext(DbContextOptions<K2_Billing_AppointmentContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TbMCreditTerm> TbMCreditTerm { get; set; }
        public virtual DbSet<TbMDeliveryType> TbMDeliveryType { get; set; }
        public virtual DbSet<TbMStatus> TbMStatus { get; set; }
        public virtual DbSet<TbRBa> TbRBa { get; set; }
        public virtual DbSet<TbRCbBa> TbRCbBa { get; set; }
        public virtual DbSet<TbRCbInvoice> TbRCbInvoice { get; set; }
        public virtual DbSet<TbRCbPackage> TbRCbPackage { get; set; }
        public virtual DbSet<TbRInvoice> TbRInvoice { get; set; }
        public virtual DbSet<TbRPackage> TbRPackage { get; set; }
        public virtual DbSet<TbSBillingAppointmentReportData> TbSBillingAppointmentReportData { get; set; }
        public virtual DbSet<TbSBillingData> TbSBillingData { get; set; }
        public virtual DbSet<TbSConfig> TbSConfig { get; set; }
        public virtual DbSet<TbSInvoiceHeader> TbSInvoiceHeader { get; set; }
        public virtual DbSet<VBillingAppointment> VBillingAppointment { get; set; }
        public virtual DbSet<VBillingAppointmentBillToCompany> VBillingAppointmentBillToCompany { get; set; }
        public virtual DbSet<VCbBillingAppointment> VCbBillingAppointment { get; set; }
        public virtual DbSet<VCbPackageList> VCbPackageList { get; set; }
        public virtual DbSet<VPackage> VPackage { get; set; }
        public virtual DbSet<VPackageList> VPackageList { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TbMCreditTerm>(entity =>
            {
                entity.HasKey(e => e.CreditTermId);

                entity.ToTable("TB_M_Credit_Term");

                entity.Property(e => e.CreditTermId)
                    .HasColumnName("Credit_Term_ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.CreditCode)
                    .HasColumnName("Credit_Code")
                    .HasMaxLength(50);

                entity.Property(e => e.CreditTermValue)
                    .HasColumnName("Credit_Term_Value")
                    .HasMaxLength(10)
                    .IsFixedLength();
            });

            modelBuilder.Entity<TbMDeliveryType>(entity =>
            {
                entity.HasKey(e => e.DeliveryTypeId);

                entity.ToTable("TB_M_Delivery_Type");

                entity.Property(e => e.DeliveryTypeId)
                    .HasColumnName("Delivery_Type_ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.DeliveryCode)
                    .HasColumnName("Delivery_Code")
                    .HasMaxLength(50);

                entity.Property(e => e.DeliveryType)
                    .HasColumnName("Delivery_Type")
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<TbMStatus>(entity =>
            {
                entity.HasKey(e => e.StatusId);

                entity.ToTable("TB_M_STATUS");

                entity.Property(e => e.StatusId)
                    .HasColumnName("STATUS_ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.Doctype)
                    .HasColumnName("DOCTYPE")
                    .HasMaxLength(50);

                entity.Property(e => e.DoctypeSub)
                    .HasColumnName("DOCTYPE_SUB")
                    .HasMaxLength(50);

                entity.Property(e => e.StatusCode)
                    .HasColumnName("STATUS_CODE")
                    .HasMaxLength(50);

                entity.Property(e => e.StatusName)
                    .HasColumnName("STATUS_NAME")
                    .HasMaxLength(100);
            });

            modelBuilder.Entity<TbRBa>(entity =>
            {
                entity.HasKey(e => e.BaId);

                entity.ToTable("TB_R_BA");

                entity.Property(e => e.BaId)
                    .HasColumnName("BA_ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.BaNo)
                    .HasColumnName("BA_No")
                    .HasMaxLength(50);

                entity.Property(e => e.CreateBy).HasMaxLength(50);

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.DeliveryLab)
                    .HasColumnName("Delivery_Lab")
                    .HasMaxLength(50);

                entity.Property(e => e.DeliveryType)
                    .HasColumnName("Delivery_Type")
                    .HasMaxLength(50);

                entity.Property(e => e.InvoiceCustCode)
                    .HasColumnName("Invoice_Cust_Code")
                    .HasMaxLength(50);

                entity.Property(e => e.InvoiceNote)
                    .HasColumnName("Invoice_Note")
                    .HasMaxLength(500);

                entity.Property(e => e.InvoiceToAddress)
                    .HasColumnName("Invoice_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.InvoiceToComany)
                    .HasColumnName("Invoice_To_Comany")
                    .HasMaxLength(500);

                entity.Property(e => e.InvoiceToPerson)
                    .HasColumnName("Invoice_To_Person")
                    .HasMaxLength(50);

                entity.Property(e => e.InvoiceToTel)
                    .HasColumnName("Invoice_To_Tel")
                    .HasMaxLength(50);

                entity.Property(e => e.PackageId).HasColumnName("Package_ID");

                entity.Property(e => e.QuoteNo)
                    .HasColumnName("Quote_No")
                    .HasMaxLength(50);

                entity.Property(e => e.ReportToComany)
                    .HasColumnName("Report_To_Comany")
                    .HasMaxLength(500);

                entity.Property(e => e.ReportsToAddress)
                    .HasColumnName("Reports_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.ReportsToTel)
                    .HasColumnName("Reports_To_Tel")
                    .HasMaxLength(50);

                entity.Property(e => e.StatusCode)
                    .HasColumnName("Status_Code")
                    .HasMaxLength(10);

                entity.Property(e => e.UpdateBy).HasMaxLength(50);

                entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<TbRCbBa>(entity =>
            {
                entity.HasKey(e => e.CbId);

                entity.ToTable("TB_R_CB_BA");

                entity.Property(e => e.CbId)
                    .HasColumnName("CB_ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.CbCreateBy)
                    .HasColumnName("CB_CreateBy")
                    .HasMaxLength(50);

                entity.Property(e => e.CbCreateDate)
                    .HasColumnName("CB_CreateDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.CbDeliveryLab)
                    .HasColumnName("CB_Delivery_Lab")
                    .HasMaxLength(50);

                entity.Property(e => e.CbDeliveryType)
                    .HasColumnName("CB_Delivery_Type")
                    .HasMaxLength(50);

                entity.Property(e => e.CbInvoiceCustCode)
                    .HasColumnName("CB_Invoice_Cust_Code")
                    .HasMaxLength(50);

                entity.Property(e => e.CbInvoiceNote)
                    .HasColumnName("CB_Invoice_Note")
                    .HasMaxLength(500);

                entity.Property(e => e.CbInvoiceToAddress)
                    .HasColumnName("CB_Invoice_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.CbInvoiceToComany)
                    .HasColumnName("CB_Invoice_To_Comany")
                    .HasMaxLength(500);

                entity.Property(e => e.CbInvoiceToPerson)
                    .HasColumnName("CB_Invoice_To_Person")
                    .HasMaxLength(50);

                entity.Property(e => e.CbInvoiceToTel)
                    .HasColumnName("CB_Invoice_To_Tel")
                    .HasMaxLength(50);

                entity.Property(e => e.CbNo)
                    .HasColumnName("CB_No")
                    .HasMaxLength(50);

                entity.Property(e => e.CbPackageId).HasColumnName("CB_Package_ID");

                entity.Property(e => e.CbQuoteNo)
                    .HasColumnName("CB_Quote_No")
                    .HasMaxLength(50);

                entity.Property(e => e.CbReportToComany)
                    .HasColumnName("CB_Report_To_Comany")
                    .HasMaxLength(500);

                entity.Property(e => e.CbReportsToAddress)
                    .HasColumnName("CB_Reports_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.CbReportsToTel)
                    .HasColumnName("CB_Reports_To_Tel")
                    .HasMaxLength(50);

                entity.Property(e => e.CbStatusCode)
                    .HasColumnName("CB_Status_Code")
                    .HasMaxLength(10);

                entity.Property(e => e.CbUpdateBy)
                    .HasColumnName("CB_UpdateBy")
                    .HasMaxLength(50);

                entity.Property(e => e.CbUpdateDate)
                    .HasColumnName("CB_UpdateDate")
                    .HasColumnType("datetime");
            });

            modelBuilder.Entity<TbRCbInvoice>(entity =>
            {
                entity.HasKey(e => e.CbInvoiceId);

                entity.ToTable("TB_R_CB_INVOICE");

                entity.Property(e => e.CbInvoiceId)
                    .HasColumnName("CB_Invoice_ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.CbBillToCompany)
                    .HasColumnName("CB_Bill_To_Company")
                    .HasMaxLength(500);

                entity.Property(e => e.CbCustCode)
                    .HasColumnName("CB_Cust_Code")
                    .HasMaxLength(50);

                entity.Property(e => e.CbDeliveryAddress)
                    .HasColumnName("CB_Delivery_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.CbDeliveryToPerson)
                    .HasColumnName("CB_Delivery_To_Person")
                    .HasMaxLength(50);

                entity.Property(e => e.CbDeliveryToTel)
                    .HasColumnName("CB_Delivery_To_Tel")
                    .HasMaxLength(50);

                entity.Property(e => e.CbId).HasColumnName("CB_ID");

                entity.Property(e => e.CbInvoiceDateOverride)
                    .HasColumnName("CB_Invoice_Date_Override")
                    .HasColumnType("datetime");

                entity.Property(e => e.CbInvoiceIssueDate)
                    .HasColumnName("CB_Invoice_Issue_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.CbInvoiceNo)
                    .HasColumnName("CB_Invoice_No")
                    .HasMaxLength(50);

                entity.Property(e => e.CbReportToComany)
                    .HasColumnName("CB_Report_To_Comany")
                    .HasMaxLength(50);

                entity.Property(e => e.CbReportsToAddress)
                    .HasColumnName("CB_Reports_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.CbReportsToTel)
                    .HasColumnName("CB_Reports_To_Tel")
                    .HasMaxLength(50);

                entity.Property(e => e.CbTotalInvoiceAmountIncVat)
                    .HasColumnName("CB_Total_Invoice_Amount_Inc_Vat")
                    .HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreateBy).HasMaxLength(50);

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.CreditTerm).HasMaxLength(10);

                entity.Property(e => e.StatusCode)
                    .HasColumnName("Status_Code")
                    .HasMaxLength(10);

                entity.Property(e => e.UpdateBy).HasMaxLength(50);

                entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<TbRCbPackage>(entity =>
            {
                entity.HasKey(e => e.CbPackageId);

                entity.ToTable("TB_R_CB_PACKAGE");

                entity.Property(e => e.CbPackageId)
                    .HasColumnName("CB_Package_ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.CbInvoiceDeliveryLab)
                    .HasColumnName("CB_Invoice_Delivery_Lab")
                    .HasMaxLength(50);

                entity.Property(e => e.CbInvoiceDeliveryPhone)
                    .HasColumnName("CB_Invoice_Delivery_Phone")
                    .HasMaxLength(50);

                entity.Property(e => e.CbInvoiceDeliveryType)
                    .HasColumnName("CB_Invoice_Delivery_Type")
                    .HasMaxLength(50);

                entity.Property(e => e.CbInvoiceToAddress)
                    .HasColumnName("CB_Invoice_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.CbInvoiceToCompany)
                    .HasColumnName("CB_Invoice_To_Company")
                    .HasMaxLength(500);

                entity.Property(e => e.CbInvoiceToCustCode)
                    .HasColumnName("CB_Invoice_To_Cust_Code")
                    .HasMaxLength(50);

                entity.Property(e => e.CbInvoiceToPerson)
                    .HasColumnName("CB_Invoice_To_Person")
                    .HasMaxLength(50);

                entity.Property(e => e.CbLogisticsDeliveryDate)
                    .HasColumnName("CB_Logistics_Delivery_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.CbPackageDeliveryDate)
                    .HasColumnName("CB_Package_Delivery_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.CbPackageDesc)
                    .HasColumnName("CB_Package_DESC")
                    .HasMaxLength(500);

                entity.Property(e => e.CbPackageName)
                    .HasColumnName("CB_Package_Name")
                    .HasMaxLength(50);

                entity.Property(e => e.CbPackageNo)
                    .HasColumnName("CB_Package_No")
                    .HasMaxLength(50);

                entity.Property(e => e.CbStatusCode)
                    .HasColumnName("CB_Status_Code")
                    .HasMaxLength(10);

                entity.Property(e => e.CreateBy).HasMaxLength(50);

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.UpdateBy).HasMaxLength(50);

                entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<TbRInvoice>(entity =>
            {
                entity.HasKey(e => e.InvoiceId);

                entity.ToTable("TB_R_INVOICE");

                entity.Property(e => e.InvoiceId)
                    .HasColumnName("Invoice_ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.BaId).HasColumnName("BA_ID");

                entity.Property(e => e.BillToCompany)
                    .HasColumnName("Bill_To_Company")
                    .HasMaxLength(500);

                entity.Property(e => e.CreateBy).HasMaxLength(50);

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.CreditTerm).HasMaxLength(10);

                entity.Property(e => e.CustCode)
                    .HasColumnName("Cust_Code")
                    .HasMaxLength(50);

                entity.Property(e => e.DeliveryAddress)
                    .HasColumnName("Delivery_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.DeliveryToPerson)
                    .HasColumnName("Delivery_To_Person")
                    .HasMaxLength(50);

                entity.Property(e => e.DeliveryToTel)
                    .HasColumnName("Delivery_To_Tel")
                    .HasMaxLength(50);

                entity.Property(e => e.InvoiceDateOverride)
                    .HasColumnName("Invoice_Date_Override")
                    .HasColumnType("datetime");

                entity.Property(e => e.InvoiceIssueDate)
                    .HasColumnName("Invoice_Issue_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.InvoiceNo)
                    .HasColumnName("Invoice_No")
                    .HasMaxLength(50);

                entity.Property(e => e.InvoiceNote).HasColumnName("Invoice_Note");

                entity.Property(e => e.InvoiceProcess)
                    .HasColumnName("Invoice_Process")
                    .HasMaxLength(500);

                entity.Property(e => e.ReportToComany)
                    .HasColumnName("Report_To_Comany")
                    .HasMaxLength(50);

                entity.Property(e => e.ReportsToAddress)
                    .HasColumnName("Reports_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.ReportsToTel)
                    .HasColumnName("Reports_To_Tel")
                    .HasMaxLength(50);

                entity.Property(e => e.StatusCode)
                    .HasColumnName("Status_Code")
                    .HasMaxLength(10);

                entity.Property(e => e.TotalInvoiceAmountIncVat)
                    .HasColumnName("Total_Invoice_Amount_Inc_Vat")
                    .HasColumnType("decimal(18, 2)");

                entity.Property(e => e.UpdateBy).HasMaxLength(50);

                entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<TbRPackage>(entity =>
            {
                entity.HasKey(e => e.PackageId);

                entity.ToTable("TB_R_PACKAGE");

                entity.Property(e => e.PackageId)
                    .HasColumnName("Package_ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.CreateBy).HasMaxLength(50);

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.InvoiceDeliveryLab)
                    .HasColumnName("Invoice_Delivery_Lab")
                    .HasMaxLength(50);

                entity.Property(e => e.InvoiceDeliveryPhone)
                    .HasColumnName("Invoice_Delivery_Phone")
                    .HasMaxLength(50);

                entity.Property(e => e.InvoiceDeliveryType)
                    .HasColumnName("Invoice_Delivery_Type")
                    .HasMaxLength(50);

                entity.Property(e => e.InvoiceToAddress)
                    .HasColumnName("Invoice_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.InvoiceToCompany)
                    .HasColumnName("Invoice_To_Company")
                    .HasMaxLength(500);

                entity.Property(e => e.InvoiceToCustCode)
                    .HasColumnName("Invoice_To_Cust_Code")
                    .HasMaxLength(50);

                entity.Property(e => e.InvoiceToPerson)
                    .HasColumnName("Invoice_To_Person")
                    .HasMaxLength(50);

                entity.Property(e => e.LogisticsDeliveryDate)
                    .HasColumnName("Logistics_Delivery_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.PackageDeliveryDate)
                    .HasColumnName("Package_Delivery_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.PackageDesc)
                    .HasColumnName("Package_DESC")
                    .HasMaxLength(500);

                entity.Property(e => e.PackageName)
                    .HasColumnName("Package_Name")
                    .HasMaxLength(50);

                entity.Property(e => e.PackageNo)
                    .HasColumnName("Package_No")
                    .HasMaxLength(50);

                entity.Property(e => e.StatusCode)
                    .HasColumnName("Status_Code")
                    .HasMaxLength(10);

                entity.Property(e => e.UpdateBy).HasMaxLength(50);

                entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<TbSBillingAppointmentReportData>(entity =>
            {
                entity.ToTable("TB_S_BillingAppointmentReportData");

                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.BillToClientCode).HasMaxLength(50);

                entity.Property(e => e.BillToContactPerson).HasMaxLength(255);

                entity.Property(e => e.CeateBy).HasMaxLength(50);

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.InvoiceDateOverride).HasColumnType("date");

                entity.Property(e => e.InvoiceIssuedDate).HasColumnType("date");
            });

            modelBuilder.Entity<TbSBillingData>(entity =>
            {
                entity.ToTable("TB_S_BillingData");

                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.Afenumber).HasColumnName("AFENumber");

                entity.Property(e => e.CoCfile).HasColumnName("CoCFile");

                entity.Property(e => e.CreateBy).HasMaxLength(50);

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.Glaccount).HasColumnName("GLAccount");

                entity.Property(e => e.InvoiceFile).IsRequired();

                entity.Property(e => e.InvoiceNumber)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.LegalSiteDescriptionLsd).HasColumnName("LegalSiteDescriptionLSD");

                entity.Property(e => e.NavaccountNumber)
                    .HasColumnName("NAVAccountNumber")
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Project)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Site)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Workorder)
                    .HasMaxLength(10)
                    .IsFixedLength();
            });

            modelBuilder.Entity<TbSConfig>(entity =>
            {
                entity.HasKey(e => e.ConfigId);

                entity.ToTable("TB_S_CONFIG");

                entity.Property(e => e.ConfigId)
                    .HasColumnName("Config_ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.ConfigName)
                    .HasColumnName("Config_Name")
                    .HasMaxLength(50);

                entity.Property(e => e.ConfigValue)
                    .HasColumnName("Config_Value")
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<TbSInvoiceHeader>(entity =>
            {
                entity.ToTable("TB_S_InvoiceHeader");

                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.CreateBy).HasMaxLength(50);

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.InvoiceIssuedDate).HasColumnType("date");
            });

            modelBuilder.Entity<VBillingAppointment>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vBillingAppointment");

                entity.Property(e => e.BaId).HasColumnName("BA_ID");

                entity.Property(e => e.BaNo)
                    .HasColumnName("BA_No")
                    .HasMaxLength(50);

                entity.Property(e => e.BillToCompany)
                    .HasColumnName("Bill_To_Company")
                    .HasMaxLength(500);

                entity.Property(e => e.CreateBy).HasMaxLength(50);

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.DeliveryName)
                    .HasColumnName("Delivery_Name")
                    .HasMaxLength(50);

                entity.Property(e => e.DeliveryType)
                    .HasColumnName("Delivery_Type")
                    .HasMaxLength(50);

                entity.Property(e => e.DiffAddress)
                    .IsRequired()
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.InvoiceCustCode)
                    .HasColumnName("Invoice_Cust_Code")
                    .HasMaxLength(50);

                entity.Property(e => e.InvoiceId).HasColumnName("Invoice_ID");

                entity.Property(e => e.InvoiceNo)
                    .HasColumnName("Invoice_No")
                    .HasMaxLength(50);

                entity.Property(e => e.InvoiceNote)
                    .HasColumnName("Invoice_Note")
                    .HasMaxLength(500);

                entity.Property(e => e.InvoiceToAddress)
                    .HasColumnName("Invoice_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.PackageId).HasColumnName("Package_ID");

                entity.Property(e => e.QuoteNo)
                    .HasColumnName("Quote_No")
                    .HasMaxLength(50);

                entity.Property(e => e.ReportsToAddress)
                    .HasColumnName("Reports_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.StatusCode)
                    .HasColumnName("Status_Code")
                    .HasMaxLength(10);

                entity.Property(e => e.StatusName)
                    .HasColumnName("STATUS_NAME")
                    .HasMaxLength(100);

                entity.Property(e => e.UpdateBy).HasMaxLength(50);

                entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<VBillingAppointmentBillToCompany>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vBillingAppointment_BillToCompany");

                entity.Property(e => e.BillToCompany)
                    .HasColumnName("Bill_To_Company")
                    .HasMaxLength(500);
            });

            modelBuilder.Entity<VCbBillingAppointment>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vCB_BillingAppointment");

                entity.Property(e => e.CbBillToCompany)
                    .HasColumnName("CB_Bill_To_Company")
                    .HasMaxLength(500);

                entity.Property(e => e.CbCreateBy)
                    .HasColumnName("CB_CreateBy")
                    .HasMaxLength(50);

                entity.Property(e => e.CbCreateDate)
                    .HasColumnName("CB_CreateDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.CbDeliveryType)
                    .HasColumnName("CB_Delivery_Type")
                    .HasMaxLength(50);

                entity.Property(e => e.CbId).HasColumnName("CB_ID");

                entity.Property(e => e.CbInvoiceCustCode)
                    .HasColumnName("CB_Invoice_Cust_Code")
                    .HasMaxLength(50);

                entity.Property(e => e.CbInvoiceId).HasColumnName("CB_Invoice_ID");

                entity.Property(e => e.CbInvoiceNo)
                    .HasColumnName("CB_Invoice_No")
                    .HasMaxLength(50);

                entity.Property(e => e.CbInvoiceNote)
                    .HasColumnName("CB_Invoice_Note")
                    .HasMaxLength(500);

                entity.Property(e => e.CbInvoiceToAddress)
                    .HasColumnName("CB_Invoice_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.CbNo)
                    .HasColumnName("CB_No")
                    .HasMaxLength(50);

                entity.Property(e => e.CbPackageId).HasColumnName("CB_Package_ID");

                entity.Property(e => e.CbQuoteNo)
                    .HasColumnName("CB_Quote_No")
                    .HasMaxLength(50);

                entity.Property(e => e.CbReportsToAddress)
                    .HasColumnName("CB_Reports_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.CbStatusCode)
                    .HasColumnName("CB_Status_Code")
                    .HasMaxLength(10);

                entity.Property(e => e.CbUpdateBy)
                    .HasColumnName("CB_UpdateBy")
                    .HasMaxLength(50);

                entity.Property(e => e.CbUpdateDate)
                    .HasColumnName("CB_UpdateDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.DeliveryName)
                    .HasColumnName("Delivery_Name")
                    .HasMaxLength(50);

                entity.Property(e => e.DiffAddress)
                    .IsRequired()
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.StatusName)
                    .HasColumnName("STATUS_NAME")
                    .HasMaxLength(100);
            });

            modelBuilder.Entity<VCbPackageList>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vCB_PackageList");

                entity.Property(e => e.CbLogisticsDeliveryDate)
                    .HasColumnName("CB_Logistics_Delivery_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.CbPackageDeliveryDate)
                    .HasColumnName("CB_Package_Delivery_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.CbPackageId).HasColumnName("CB_Package_ID");

                entity.Property(e => e.CbPackageName)
                    .HasColumnName("CB_Package_Name")
                    .HasMaxLength(50);

                entity.Property(e => e.CbPackageNo)
                    .HasColumnName("CB_Package_No")
                    .HasMaxLength(50);

                entity.Property(e => e.CbStatusCode)
                    .HasColumnName("CB_Status_Code")
                    .HasMaxLength(10);

                entity.Property(e => e.CreateBy).HasMaxLength(50);

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.StatusName)
                    .HasColumnName("STATUS_NAME")
                    .HasMaxLength(100);
            });

            modelBuilder.Entity<VPackage>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vPackage");

                entity.Property(e => e.BaCreateBy)
                    .HasColumnName("BA_CreateBy")
                    .HasMaxLength(50);

                entity.Property(e => e.BaCreateDate)
                    .HasColumnName("BA_CreateDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.BaId).HasColumnName("BA_ID");

                entity.Property(e => e.BaNo)
                    .HasColumnName("BA_No")
                    .HasMaxLength(50);

                entity.Property(e => e.BillToCompany)
                    .HasColumnName("Bill_To_Company")
                    .HasMaxLength(500);

                entity.Property(e => e.CreditTerm).HasMaxLength(10);

                entity.Property(e => e.CustCode)
                    .HasColumnName("Cust_Code")
                    .HasMaxLength(50);

                entity.Property(e => e.DeliveryAddress)
                    .HasColumnName("Delivery_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.DeliveryToPerson)
                    .HasColumnName("Delivery_To_Person")
                    .HasMaxLength(50);

                entity.Property(e => e.DeliveryToTel)
                    .HasColumnName("Delivery_To_Tel")
                    .HasMaxLength(50);

                entity.Property(e => e.DeliveryType)
                    .HasColumnName("Delivery_Type")
                    .HasMaxLength(50);

                entity.Property(e => e.DiffAddress)
                    .IsRequired()
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.Expr1).HasMaxLength(100);

                entity.Property(e => e.InvCreateBy)
                    .HasColumnName("inv_CreateBy")
                    .HasMaxLength(50);

                entity.Property(e => e.InvCreateDate)
                    .HasColumnName("inv_CreateDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.InvoiceDateOverride)
                    .HasColumnName("Invoice_Date_Override")
                    .HasColumnType("datetime");

                entity.Property(e => e.InvoiceId).HasColumnName("Invoice_ID");

                entity.Property(e => e.InvoiceIssueDate)
                    .HasColumnName("Invoice_Issue_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.InvoiceNo)
                    .HasColumnName("Invoice_No")
                    .HasMaxLength(50);

                entity.Property(e => e.InvoiceNote)
                    .HasColumnName("Invoice_Note")
                    .HasMaxLength(500);

                entity.Property(e => e.LogisticsDeliveryDate)
                    .HasColumnName("Logistics_Delivery_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.PackCreateBy)
                    .HasColumnName("pack_CreateBy")
                    .HasMaxLength(50);

                entity.Property(e => e.PackCreateDate)
                    .HasColumnName("pack_CreateDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.PackageDeliveryDate)
                    .HasColumnName("Package_Delivery_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.PackageId).HasColumnName("Package_ID");

                entity.Property(e => e.PackageName)
                    .HasColumnName("Package_Name")
                    .HasMaxLength(50);

                entity.Property(e => e.PackageNo)
                    .HasColumnName("Package_No")
                    .HasMaxLength(50);

                entity.Property(e => e.QuoteNo)
                    .HasColumnName("Quote_No")
                    .HasMaxLength(50);

                entity.Property(e => e.ReportToComany)
                    .HasColumnName("Report_To_Comany")
                    .HasMaxLength(50);

                entity.Property(e => e.ReportsToAddress)
                    .HasColumnName("Reports_To_Address")
                    .HasMaxLength(500);

                entity.Property(e => e.ReportsToTel)
                    .HasColumnName("Reports_To_Tel")
                    .HasMaxLength(50);

                entity.Property(e => e.StatusCode)
                    .HasColumnName("Status_Code")
                    .HasMaxLength(10);

                entity.Property(e => e.StatusName)
                    .HasColumnName("Status_Name")
                    .HasMaxLength(50);

                entity.Property(e => e.TotalInvoiceAmountIncVat)
                    .HasColumnName("Total_Invoice_Amount_Inc_Vat")
                    .HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<VPackageList>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vPackageList");

                entity.Property(e => e.CreateBy).HasMaxLength(50);

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.LogisticsDeliveryDate)
                    .HasColumnName("Logistics_Delivery_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.PackageDeliveryDate)
                    .HasColumnName("Package_Delivery_Date")
                    .HasColumnType("datetime");

                entity.Property(e => e.PackageId).HasColumnName("Package_ID");

                entity.Property(e => e.PackageName)
                    .HasColumnName("Package_Name")
                    .HasMaxLength(50);

                entity.Property(e => e.PackageNo)
                    .HasColumnName("Package_No")
                    .HasMaxLength(50);

                entity.Property(e => e.StatusCode)
                    .HasColumnName("Status_Code")
                    .HasMaxLength(10);

                entity.Property(e => e.StatusName)
                    .HasColumnName("STATUS_NAME")
                    .HasMaxLength(100);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}