// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class TbMCreditTerm
    {
        public Guid CreditTermId { get; set; }
        public string CreditCode { get; set; }
        public string CreditTermValue { get; set; }
    }
}