// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class TbMStatus
    {
        public Guid StatusId { get; set; }
        public string StatusCode { get; set; }
        public string StatusName { get; set; }
        public string Doctype { get; set; }
        public string DoctypeSub { get; set; }
    }
}