// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class TbRCbInvoice
    {
        public Guid CbInvoiceId { get; set; }
        public Guid? CbId { get; set; }
        public string CbInvoiceNo { get; set; }
        public string CbCustCode { get; set; }
        public string CbBillToCompany { get; set; }
        public string CbDeliveryAddress { get; set; }
        public string CbDeliveryToPerson { get; set; }
        public string CbDeliveryToTel { get; set; }
        public string CbReportToComany { get; set; }
        public string CbReportsToAddress { get; set; }
        public string CbReportsToTel { get; set; }
        public DateTime? CbInvoiceIssueDate { get; set; }
        public DateTime? CbInvoiceDateOverride { get; set; }
        public decimal? CbTotalInvoiceAmountIncVat { get; set; }
        public string CreditTerm { get; set; }
        public string StatusCode { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    }
}