// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class TbRCbBa
    {
        public Guid CbId { get; set; }
        public Guid? CbPackageId { get; set; }
        public string CbNo { get; set; }
        public string CbQuoteNo { get; set; }
        public string CbInvoiceToComany { get; set; }
        public string CbInvoiceToPerson { get; set; }
        public string CbInvoiceToAddress { get; set; }
        public string CbInvoiceCustCode { get; set; }
        public string CbInvoiceNote { get; set; }
        public string CbReportToComany { get; set; }
        public string CbReportsToAddress { get; set; }
        public string CbReportsToTel { get; set; }
        public string CbInvoiceToTel { get; set; }
        public string CbDeliveryType { get; set; }
        public string CbDeliveryLab { get; set; }
        public string CbStatusCode { get; set; }
        public DateTime? CbCreateDate { get; set; }
        public string CbCreateBy { get; set; }
        public DateTime? CbUpdateDate { get; set; }
        public string CbUpdateBy { get; set; }
    }
}