// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class TbRInvoice
    {
        public Guid InvoiceId { get; set; }
        public Guid? BaId { get; set; }
        public string InvoiceNo { get; set; }
        public string CustCode { get; set; }
        public string BillToCompany { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryToPerson { get; set; }
        public string DeliveryToTel { get; set; }
        public string ReportToComany { get; set; }
        public string ReportsToAddress { get; set; }
        public string ReportsToTel { get; set; }
        public DateTime? InvoiceIssueDate { get; set; }
        public DateTime? InvoiceDateOverride { get; set; }
        public string InvoiceNote { get; set; }
        public string InvoiceProcess { get; set; }
        public decimal? TotalInvoiceAmountIncVat { get; set; }
        public string CreditTerm { get; set; }
        public string StatusCode { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    }
}