// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class TbRPackage
    {
        public Guid PackageId { get; set; }
        public string PackageNo { get; set; }
        public string PackageName { get; set; }
        public DateTime? PackageDeliveryDate { get; set; }
        public string PackageDesc { get; set; }
        public string InvoiceToAddress { get; set; }
        public string InvoiceToPerson { get; set; }
        public string InvoiceToCustCode { get; set; }
        public string InvoiceToCompany { get; set; }
        public string InvoiceDeliveryPhone { get; set; }
        public string InvoiceDeliveryType { get; set; }
        public string InvoiceDeliveryLab { get; set; }
        public DateTime? LogisticsDeliveryDate { get; set; }
        public string StatusCode { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    }
}