// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class TbSBillingData
    {
        public Guid Id { get; set; }
        public string InvoiceNumber { get; set; }
        public string Workorder { get; set; }
        public string Site { get; set; }
        public string NavaccountNumber { get; set; }
        public string Project { get; set; }
        public string PurchaseOrder { get; set; }
        public string ReportToContact { get; set; }
        public string ReportToOffice { get; set; }
        public string ReportToClient { get; set; }
        public string InvoiceContact { get; set; }
        public string Laboratory { get; set; }
        public string ClientManager { get; set; }
        public string ActivityCode { get; set; }
        public string Afenumber { get; set; }
        public string ApproverCode { get; set; }
        public string ContractNumber { get; set; }
        public string CostCenterClient { get; set; }
        public string Glaccount { get; set; }
        public string LegalSiteDescriptionLsd { get; set; }
        public string ProjectManagerClientSide { get; set; }
        public string InvoiceFile { get; set; }
        public string CoCfile { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateBy { get; set; }
    }
}