// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class usp_CriteriaSearchBillingAppointmentResult
    {
        public Guid Package_ID { get; set; }
        public string Package_No { get; set; }
        public string Package_Name { get; set; }
        public DateTime? Package_Delivery_Date { get; set; }
        public DateTime? Logistics_Delivery_Date { get; set; }
        public string Status_Code { get; set; }
        public string STATUS_NAME { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}
