// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class usp_AdhocListInvoiceByInvoiceAddressResult
    {
        public Guid Invoice_ID { get; set; }
        public string Invoice_No { get; set; }
        public DateTime? Invoice_Issue_Date { get; set; }
        public DateTime? Invoice_Date_Override { get; set; }
        public string Bill_To_Company { get; set; }
        public string Delivery_Address { get; set; }
        public string Delivery_To_Person { get; set; }
    }
}
