// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class VBillingAppointmentBillToCompany
    {
        public string BillToCompany { get; set; }
    }
}