// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class VCbPackageList
    {
        public Guid CbPackageId { get; set; }
        public string CbPackageNo { get; set; }
        public string CbPackageName { get; set; }
        public DateTime? CbPackageDeliveryDate { get; set; }
        public DateTime? CbLogisticsDeliveryDate { get; set; }
        public string CbStatusCode { get; set; }
        public string StatusName { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}