// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class VPackage
    {
        public Guid? PackageId { get; set; }
        public Guid? BaId { get; set; }
        public Guid InvoiceId { get; set; }
        public string PackageNo { get; set; }
        public string PackageName { get; set; }
        public string BaNo { get; set; }
        public string InvoiceNo { get; set; }
        public string QuoteNo { get; set; }
        public string CustCode { get; set; }
        public string BillToCompany { get; set; }
        public string DeliveryToPerson { get; set; }
        public string DeliveryToTel { get; set; }
        public string DeliveryAddress { get; set; }
        public string ReportToComany { get; set; }
        public string ReportsToTel { get; set; }
        public string ReportsToAddress { get; set; }
        public string InvoiceNote { get; set; }
        public string DiffAddress { get; set; }
        public DateTime? InvoiceIssueDate { get; set; }
        public DateTime? InvoiceDateOverride { get; set; }
        public decimal? TotalInvoiceAmountIncVat { get; set; }
        public string CreditTerm { get; set; }
        public string DeliveryType { get; set; }
        public string StatusName { get; set; }
        public DateTime? PackageDeliveryDate { get; set; }
        public DateTime? LogisticsDeliveryDate { get; set; }
        public string StatusCode { get; set; }
        public string Expr1 { get; set; }
        public string PackCreateBy { get; set; }
        public DateTime? PackCreateDate { get; set; }
        public string BaCreateBy { get; set; }
        public DateTime? BaCreateDate { get; set; }
        public string InvCreateBy { get; set; }
        public DateTime? InvCreateDate { get; set; }
    }
}