// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class VPackageList
    {
        public Guid PackageId { get; set; }
        public string PackageNo { get; set; }
        public string PackageName { get; set; }
        public DateTime? PackageDeliveryDate { get; set; }
        public DateTime? LogisticsDeliveryDate { get; set; }
        public string StatusCode { get; set; }
        public string StatusName { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}